#apiVersion: v1
#kind: Service
#metadata:
#  name: petclinic-visits-service-service
#  namespace: petclinic-dev
#spec:
#  type: NodePort   
#  selector:
#    app: petclinic-visits-service
#  ports:
#    - name: tcp
#      port: 8083         
#      targetPort: 8083    
#      nodePort: 30083     
#  sessionAffinity: None
#  internalTrafficPolicy: Cluster
#  ipFamilies:
#    - IPv4
#  ipFamilyPolicy: SingleStack
