apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic-api-gateway
  name: petclinic-api-gateway-deployment
  namespace: petclinic-dev
spec:
  replicas: 1
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      app: petclinic-api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: petclinic-api-gateway
      namespace: petclinic-dev
    spec:
      containers:
        - image: thuanlp/spring-petclinic-api-gateway:latest
          imagePullPolicy: Always
          name: petclinic-api-gateway
          ports:
            - containerPort: 8080
              name: tcp
              protocol: TCP
          resources:
            requests:
              memory: "350Mi"
              cpu: "15m"
            limits:
              memory: "450Mi"
              cpu: "20m"
          volumeMounts:
            - mountPath: /app/config/application.properties
              name: petclinic-api-gateway-application-properties-config-volume
              subPath: application.properties
      initContainers:
        - name: wait-for-config-server
          image: busybox:1.28
          command:
            ["sh", "-c", "until curl -s http://petclinic-config-server-service:8888/; do echo waiting for config server; sleep 5; done"]
      
        - name: wait-for-discovery-server
          image: busybox:1.28
          command:
            ["sh", "-c", "until curl -s http://spring-petclinic-discovery-server:8761/; do echo waiting for discovery server; sleep 5; done"]
      imagePullSecrets:
      - name: dockerhub
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: petclinic-api-gateway-application-properties-configmap
          name: petclinic-api-gateway-application-properties-config-volume