
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic-admin-server
  name: petclinic-admin-server-deployment
  namespace: petclinic-dev
spec:
  replicas: 1
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      app: petclinic-admin-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: petclinic-admin-server
      namespace: petclinic-dev
    spec:
      containers:
        - image: thuanlp/spring-petclinic-admin-server:latest
          imagePullPolicy: Always
          name: petclinic-admin-server
          ports:
            - containerPort: 9090
              name: tcp
              protocol: TCP
          resources:
            requests:
              memory: "350Mi"
              cpu: "20m"
            limits:
              memory: "400Mi"
              cpu: "30m"
          volumeMounts:
            - mountPath: /app/config/application.properties
              name: petclinic-admin-server-application-properties-config-volume
              subPath: application.properties
      imagePullSecrets:
      - name: dockerhub
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: petclinic-admin-server-application-properties-configmap
          name: petclinic-admin-server-application-properties-config-volume
          
